source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MowingoSDK_Example', :exclusive => true do
  pod "MowingoSDK", :path => "../"
end

target 'MowingoSDK_Tests', :exclusive => true do
  pod "MowingoSDK", :path => "../"

  
end
